name: ci

on: repository_dispatch

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Set GitHub User Info
        run: |
          git config --global user.email ${GIT_ADDRESS}
          git config --global user.name ${GIT_USERNAME}
          git remote set-url origin https://${GIT_USERNAME}:${GIT_SECRET}@github.com/kenchon/artworks
      - name: Install Dependencies
        run: yarn install
      - name: Build and Deploy
        run: yarn deploy
        env:
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist
